name: Windows RDP Access
on: workflow_dispatch
jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
      
      - name: リモートデスクトップを有効化
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -value 1
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      
      - name: RDPパフォーマンス最適化（FPS向上、レイテンシ低減）
        run: |
          # Group Policy Editorを有効化（必要に応じて）
          if (-not (Get-Command gpedit.msc -ErrorAction SilentlyContinue)) {
            dism /online /enable-feature /featurename:Microsoft-GroupPolicy-Editor /all /norestart
          }
          # H.264/AVC 444 Graphics Modeを優先
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -Name "AVC444ModePreferred" -Value 1 -Type DWord -Force
          # 最大FPSを60に設定
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -Name "MaxFps" -Value 60 -Type DWord -Force
          # 帯域最適化
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -Name "fOptimizeBandwidth" -Value 1 -Type DWord -Force
          # ハードウェアエンコーディング有効化（GPU使用）
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -Name "fEnableWddmDriver" -Value 1 -Type DWord -Force
          # 色深度を16-bitに制限（帯域節約）
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -Name "ColorDepth" -Value 4 -Type DWord -Force
      
      - name: オーディオ最適化（音声ずれ低減）
        run: |
          # オーディオキャプチャとリダイレクション有効化
          if (-not (Test-Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services")) { New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -Force }
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -name "fDisableAudioCapture" -value 0 -Type DWORD -Force
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -name "fEnableAudioRedirection" -value 1 -Type DWORD -Force
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "fDisableAudioRedirection" -value 0 -Force
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "fEnableAudioCompression" -value 1 -Force
          # オーディオ品質をHighに設定（圧縮を減らしレイテンシ低減）
          Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" -Name "AudioPlaybackQuality" -Value 2 -Type DWord -Force  # 0=Dynamic, 1=Medium, 2=High
          # オーディオサービス有効化
          Set-Service -Name "Audiosrv" -StartupType Automatic
          Start-Service -Name "Audiosrv"
          Set-Service -Name "AudioEndpointBuilder" -StartupType Automatic
          Start-Service -Name "AudioEndpointBuilder"
      
      - name: ネットワーク最適化（帯域無制限、レイテンシ低減）
        run: |
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "MaxBandwidth" -value 0xffffffff -Type DWORD -Force
          # 帯域検出無効化
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\TermService\Parameters' -Name 'EnableBandwidthDetection' -Value 0 -Type DWord -Force
          # 視覚効果無効化（画面更新減らす）
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" -Name "VisualFXSetting" -Value 2 -Force
      
      - name: RDPユーザーを作成
        run: |
          $securePassword = ConvertTo-SecureString "${{ secrets.RDP_PASSWORD }}" -AsPlainText -Force
          New-LocalUser -Name "mainadmin" -Password $securePassword -FullName "RDP Admin" -Description "RDP access user" -AccountNeverExpires -PasswordNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "mainadmin"
      
      - name: Boreツールをダウンロード
        run: |
          Invoke-WebRequest -Uri https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-pc-windows-msvc.zip -OutFile bore.zip
          Expand-Archive bore.zip -DestinationPath . -Force
          Move-Item -Path (Get-ChildItem -Recurse -Filter "bore.exe").FullName -Destination . -Force
      
      - name: Boreトンネルを開始とポート出力
        run: |
          # Boreプロセス起動とポート取得
          $rdpProcess = Start-Process -FilePath ".\bore.exe" -ArgumentList "local 3389 --to bore.pub" -NoNewWindow -PassThru
          Start-Sleep -Seconds 5
          $rdpPort = (Get-Content -Path ".\bore.log" -Tail 1) -replace '.*:(\d+).*', '$1'  # ログからポート抽出（仮定）
          Write-Output "RDP Port: $rdpPort"
          
          Write-Output "RDP接続: bore.pub:$rdpPort (ユーザー: mainadmin, パスワード: secrets)"
          
          # 維持ループ
          while ($true) {
            Start-Sleep -Seconds 60
            Write-Output "$(Get-Date): RDP接続を維持中..."
          }
